"""Auto-regenerate MANIFEST.md by scanning the v2 dataset (accurate counts)."""
import json, csv
from pathlib import Path
BASE = Path("/home/ujjwal/Documents/J.A.R.V.I.S./data/hackathons/tata-steel-2026/round_2/dataforge/datasets/steel-maintenance-flagship")

def rows(p):
    try:
        with open(p) as f: return sum(1 for _ in f) - 1
    except Exception: return "?"
def lines(p):
    try:
        with open(p) as f: return sum(1 for l in f if l.strip())
    except Exception: return "?"

sp = json.loads((BASE/"SPEC"/"ground_truth_spine.json").read_text())
n_fail = sum(1 for s in sp["failure_scenario_catalog"] if s["label"]=="FAILURE")
n_norm = sum(1 for s in sp["failure_scenario_catalog"] if s["label"]=="NORMAL")

csvs = sorted(BASE.rglob("*.csv"))
jsonls = sorted(BASE.rglob("*.jsonl"))
mds = sorted(BASE.rglob("*.md"))
total_rows = sum(r for p in csvs if isinstance(r:=rows(p),int))

L = []
L.append("# MANIFEST — Steel Maintenance Wizard Flagship Dataset (v2.0)\n")
L.append(f"**Data version:** 2.0 (gap-fix rebuild 2026-06-10) · **Spine:** 1.0.0 · **Site:** TATA_JSR (synthetic)\n")
L.append("Auto-generated by `gen_manifest_v2.py`. v2 fixes the temporal-join + ML-trainability gaps from `GAP_ANALYSIS.md`; see `BUILD_v2_LOG.md` and `GAP_ANALYSIS_v2.md`.\n")
L.append("## Headline\n")
L.append(f"- **{len(csvs)} CSV** files · **{total_rows:,} data rows** · **{len(jsonls)} JSONL** · **{len(mds)} Markdown** docs")
L.append(f"- Spine: 15 assets / 13 classes · {n_fail} FAILURE + {n_norm} NORMAL archetypes · 44 spares")
import pandas as _pd
_nep=_pd.read_csv(BASE/"condition_monitoring"/"episodes_manifest.csv").shape[0]
L.append(f"- **{_nep} run-to-failure EPISODES** (8-11/asset) · split column (train/val/test) · run_id for LORO-CV")
L.append(f"- 0 orphans incl. temporal/causal join (incident->run->sensor, delay/fault/defect/feedback->incident)\n")

L.append("## Full CSV inventory\n")
L.append("| File | Rows |")
L.append("|---|---|")
for p in csvs:
    L.append(f"| `{p.relative_to(BASE)}` | {rows(p):,} |" if isinstance(rows(p),int) else f"| `{p.relative_to(BASE)}` | ? |")

L.append("\n## JSONL inventory\n")
L.append("| File | Records |\n|---|---|")
for p in jsonls:
    L.append(f"| `{p.relative_to(BASE)}` | {lines(p)} |")

L.append("\n## Document inventory (Markdown)\n")
L.append(f"Total markdown docs: **{len(mds)}** "
         f"(equipment manuals, SOPs, RCA reports, diagrams [P&ID/ELEC/LUBE/FTA/LOTO], summaries, cards).\n")

L.append("## PS §4 input coverage (all FULL)\n")
L.append("| PS category | Backing files |\n|---|---|")
L.append("| 4.1 Operational & failure | `operational_failure/*` (incidents w/ ISO-14224+run_id FK, delay logs+FK, fault msgs+FK, defect events, 25 RCA) |")
L.append("| 4.2 Condition monitoring | `condition_monitoring/*` (raw historian, long, dense by_equipment, rul_trajectories, anomaly_alerts, event_stream, episodes_manifest) |")
L.append("| 4.3 Knowledge & docs | `knowledge_docs/*` (13 manuals, 13 SOPs, 20 diagrams, spare catalog, historical records) |")
L.append("| 4.4 User interaction | `user_interaction/*` (nl_queries+rubric, multiturn, troubleshooting, maintenance_feedback) |")
L.append("| Additional | `additional/*` (equipment master, alarm DB, work orders, process_flow_graph.json, OEM/handover) |")

(BASE/"MANIFEST.md").write_text("\n".join(L))
print(f"MANIFEST.md regenerated: {len(csvs)} csv ({total_rows:,} rows), {len(jsonls)} jsonl, {len(mds)} md")
