import type { AuditReport, AuditRunView, Finding, FindingsPage } from "../types";
import findingsRaw from "./findings.json";

// Inline the report markdown to avoid webpack .md module complexity
const reportMarkdown = `# Security Audit Report

**Audit ID:** \`2d919643-fbfa-4b2a-a1fd-e70b91905939\`
**Target:** \`/home/ujjwal/Documents/J.A.R.V.I.S./My Apps/apps/enginerd\`
**Generated:** 2026-06-06 03:57 UTC
**Scanners:** semgrep, trivy, osv, gitleaks, trufflehog

---

## Executive Summary

AuditAgent completed a full SAST + SCA + secrets scan of the **EngiNerd** codebase. Of **52 raw findings**, the automated verification layer filtered **37 false positives**, leaving **15 actionable findings** requiring human review or immediate remediation.

> **Verdict:** Two confirmed secrets in \`.env.local\` require immediate rotation. Seven Next.js CVEs warrant dependency upgrade. The secrets in markdown documentation files are verified false positives.

---

## Severity Distribution

| Severity | Raw | False Positives | Actionable |
|---|---|---|---|
| Critical | 8 | 5 | 3 |
| High | 9 | 2 | 7 |
| Medium | 12 | 4 | 8 |
| Low | 21 | 18 | 3 |
| Info | 2 | 2 | 0 |
| **Total** | **52** | **37** | **15** |

---

## Critical Findings

### 1. Confirmed Auth Secret in \`.env.local\`

**Finding ID:** \`12f21085-9cfd-40ea-934f-4191eea75c1b\`
**Scanner:** gitleaks | **Rule:** \`gitleaks.generic-api-key\`
**CVSS 4.0:** 5.5 | **CWE:** CWE-798

\`\`\`
AUTH_SECRET=gf4G...Ipc= detected in .env.local line 1
\`\`\`

**Verification:** Sonnet confirmed this is a real NextAuth/Auth.js session-signing key. CVSS downgraded from 9.3 to 5.5 (AV:L).

**Remediation:**
1. Verify \`.env.local\` is in \`.gitignore\`
2. Run \`git log --all --full-history -- '**/.env.local'\` to audit history
3. If found in any commit: \`git filter-repo --path .env.local --invert-paths\` + rotate value
4. Replace with platform env var (Vercel dashboard / Doppler / 1Password Secrets)

---

### 2. Confirmed Google OAuth Secret

**Finding ID:** \`1d273532-0a9a-44e5-8d8f-0228cc752569\`
**Scanner:** gitleaks | **CVSS 4.0:** 7.5

\`\`\`
AUTH_GOOGLE_SECRET=GOCSPX-... detected in .env.local line 19
\`\`\`

**Remediation:** Revoke at console.cloud.google.com immediately. Audit git history.

---

### 3. Confirmed Live Postgres Connection String

**Finding ID:** \`316748c8-43a0-44ee-a5b6-79462ecdedef\`
**Scanner:** trufflehog | **CVSS 4.0:** 7.5

\`\`\`
Detector: Postgres | Secret: post...5432 | (VERIFIED LIVE)
\`\`\`

**Remediation:** Change database password immediately. Rotate credentials. Use a secrets manager.

---

## High Severity: Next.js CVEs

| GHSA | Title | CVSS |
|---|---|---|
| GHSA-267c-6grr-h53f | Middleware/Proxy bypass via segment-prefetch | 8.8 |
| GHSA-26hh-7cqf-hhc6 | Middleware bypass incomplete fix follow-up | 8.8 |
| GHSA-36qx-fr4f-26g5 | Middleware bypass via Pages Router i18n | 8.8 |
| GHSA-492v-c6pp-mqqv | Middleware bypass via dynamic route injection | 8.8 |
| GHSA-8h8q-6873-q5fj | DoS via Server Components | 8.8 |
| GHSA-c4j6-fc7j-m34r | SSRF via WebSocket upgrades | 8.8 |
| GHSA-mg66-mrh9-m8jx | DoS via Cache Component connection exhaustion | 8.8 |

**Recommended action:** \`npm install next@latest\`

---

## Remediation Checklist

- [ ] Rotate AUTH_SECRET (NextAuth session key)
- [ ] Revoke and regenerate Google OAuth client secret
- [ ] Rotate live Postgres database password
- [ ] Upgrade \`next\` to latest patched version
- [ ] Upgrade \`axios\` to latest
- [ ] Verify all \`.env*\` files are in \`.gitignore\`
- [ ] Audit git history for accidental credential commits

---

*Generated by AuditAgent (Jarvis). Defensive-only. Authorized targets only.*
`;

const DEMO_AUDIT_ID = "2d919643-fbfa-4b2a-a1fd-e70b91905939";

export const demoFindings: Finding[] = findingsRaw as Finding[];

const fpCount = demoFindings.filter((f) => f.verification_status === "false_positive").length;
const actionableCount = demoFindings.filter((f) => f.is_actionable).length;

export const demoAuditRunView: AuditRunView = {
  audit_id: DEMO_AUDIT_ID,
  audit_state: "done",
  target_uri: "/home/ujjwal/Documents/J.A.R.V.I.S./My Apps/apps/enginerd",
  user_id: "ujjwal",
  created_at: "2026-06-06T03:45:00Z",
  updated_at: "2026-06-06T03:57:00Z",
  progress_pct: 100,
  total_findings: actionableCount,
  cost_usd_total: 0.31,
  error: null,
};

const bySeverity: Record<string, number> = {};
for (const f of demoFindings) {
  bySeverity[f.severity] = (bySeverity[f.severity] ?? 0) + 1;
}

export const demoReport: AuditReport = {
  audit_id: DEMO_AUDIT_ID,
  generated_at: "2026-06-06T03:57:00Z",
  target_uri: demoAuditRunView.target_uri,
  total_findings: demoFindings.length,
  by_severity: bySeverity,
  top_findings: demoFindings
    .filter((f) => f.cvss_score !== null)
    .sort((a, b) => (b.cvss_score ?? 0) - (a.cvss_score ?? 0))
    .slice(0, 10),
  markdown_body: reportMarkdown,
  json_findings: demoFindings,
  cvss_distribution: {},
};

export function getDemoFindingsPage(params: {
  limit?: number;
  cursor?: string;
  severity?: string;
  status?: string;
}): FindingsPage {
  const { limit = 50, cursor, severity, status } = params;

  let filtered = [...demoFindings];

  if (severity) {
    const sevs = severity.split(",").map((s) => s.trim().toLowerCase());
    filtered = filtered.filter((f) => sevs.includes(f.severity));
  }
  if (status) {
    const statuses = status.split(",").map((s) => s.trim().toLowerCase());
    filtered = filtered.filter((f) => statuses.includes(f.verification_status));
  }

  filtered.sort(
    (a, b) =>
      (b.cvss_score ?? 0) - (a.cvss_score ?? 0)
  );

  const total = filtered.length;
  const offset = cursor && /^\d+$/.test(cursor) ? parseInt(cursor) : 0;
  const page = filtered.slice(offset, offset + limit);
  const nextOffset = offset + limit;

  return {
    items: page,
    next_cursor: nextOffset < total ? String(nextOffset) : null,
    total,
  };
}

export const DEMO_FP_COUNT = fpCount;
export const DEMO_ACTIONABLE_COUNT = actionableCount;
export const DEMO_RAW_COUNT = demoFindings.length;
