"""
V26 — V4 with BorderlineSMOTE-1 (replace vanilla SMOTE)
=========================================================

Single change from V4:
  - Vanilla SMOTE(sampling_strategy=0.3, k_neighbors=3)
    replaced with BorderlineSMOTE(kind='borderline-1', sampling_strategy=0.3,
                                   k_neighbors=3, m_neighbors=10)

Fallback cascade:
  1. BorderlineSMOTE-1   (primary)
  2. BorderlineSMOTE-2   (if BL-1 finds zero borderline samples in a fold)
  3. SMOTEENN            (if both BL variants fail)

All else identical to V4:
  - 51 features from v4_final_features.json
  - 5-fold StratifiedKFold(seed=42)
  - LightGBM + XGBoost + CatBoost base learners
  - Logistic Regression meta-learner + Platt calibration
  - Score-aware exact-unique-threshold sweep, max (R+P)/2

Outputs (all written to build_v26/):
  oof_v26.parquet         — CoilID, oof_meta, Y
  chosen_threshold_v26.json
  expected_submission.csv — CoilID, Y
"""

from __future__ import annotations

import json
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import SMOTE, BorderlineSMOTE
from imblearn.under_sampling import EditedNearestNeighbours
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import lightgbm as lgb
import xgboost as xgb

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

# Paths
ROUND1 = Path(__file__).resolve().parents[1]
V4_DIR = ROUND1 / "build_v4"
V26_DIR = ROUND1 / "build_v26"

V4_TRAIN_PARQUET = V4_DIR / "train_v4.parquet"
V4_TEST_PARQUET  = V4_DIR / "test_v4.parquet"
V4_FEATURES_JSON = V4_DIR / "v4_final_features.json"

# Hyper-parameters (same as V4)
LGB_PARAMS = dict(
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=-1,
    min_child_samples=10,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    scale_pos_weight=19.5,
    random_state=42,
    n_jobs=-1,
    verbose=-1,
)

XGB_PARAMS = dict(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=5,
    scale_pos_weight=19.5,
    eval_metric="logloss",
    early_stopping_rounds=50,
    random_state=42,
    n_jobs=-1,
    verbosity=0,
)

CAT_PARAMS = dict(
    iterations=500,
    learning_rate=0.05,
    depth=5,
    l2_leaf_reg=3,
    scale_pos_weight=19.5,
    random_seed=42,
    verbose=False,
)


def make_borderline_smote_1():
    return BorderlineSMOTE(
        sampling_strategy=0.3,
        k_neighbors=3,
        m_neighbors=10,
        kind="borderline-1",
        random_state=42,
    )


def make_borderline_smote_2():
    return BorderlineSMOTE(
        sampling_strategy=0.3,
        k_neighbors=3,
        m_neighbors=10,
        kind="borderline-2",
        random_state=42,
    )


def make_smoteenn():
    return SMOTEENN(
        sampling_strategy=0.3,
        random_state=42,
        smote=SMOTE(k_neighbors=3, random_state=42),
        enn=EditedNearestNeighbours(n_neighbors=3),
    )


def resample_fold(X_tr, y_tr, fold_idx):
    n_pos_before = int(y_tr.sum())

    # Attempt 1: BorderlineSMOTE-1
    try:
        sampler = make_borderline_smote_1()
        X_res, y_res = sampler.fit_resample(X_tr, y_tr)
        n_syn = int(y_res.sum()) - n_pos_before
        if n_syn < 1:
            raise ValueError("Zero synthetic samples generated by BL-1")
        print(f"  [Fold {fold_idx}] BorderlineSMOTE-1: {n_pos_before} -> {int(y_res.sum())} positives (+{n_syn} synthetic)")
        return X_res, y_res, "borderline-1"
    except Exception as e:
        print(f"  [Fold {fold_idx}] BL-1 FAILED ({e}), trying BL-2 ...")

    # Attempt 2: BorderlineSMOTE-2
    try:
        sampler = make_borderline_smote_2()
        X_res, y_res = sampler.fit_resample(X_tr, y_tr)
        n_syn = int(y_res.sum()) - n_pos_before
        if n_syn < 1:
            raise ValueError("Zero synthetic samples generated by BL-2")
        print(f"  [Fold {fold_idx}] BorderlineSMOTE-2 (fallback): {n_pos_before} -> {int(y_res.sum())} positives (+{n_syn} synthetic)")
        return X_res, y_res, "borderline-2"
    except Exception as e:
        print(f"  [Fold {fold_idx}] BL-2 FAILED ({e}), falling back to SMOTEENN ...")

    # Attempt 3: SMOTEENN
    sampler = make_smoteenn()
    X_res, y_res = sampler.fit_resample(X_tr, y_tr)
    n_syn = int(y_res.sum()) - n_pos_before
    print(f"  [Fold {fold_idx}] SMOTEENN (fallback): {n_pos_before} -> {int(y_res.sum())} positives (+{n_syn} synthetic)")
    return X_res, y_res, "smoteenn"


def main():
    print("=" * 65)
    print("V26 - BorderlineSMOTE-1 (drop-in replace for vanilla SMOTE)")
    print("=" * 65)

    train = pd.read_parquet(V4_TRAIN_PARQUET)
    test  = pd.read_parquet(V4_TEST_PARQUET)

    with open(V4_FEATURES_JSON) as fh:
        feat_meta = json.load(fh)
    features = feat_meta["features"]

    assert len(features) == 51
    assert all(f in train.columns for f in features)
    assert all(f in test.columns  for f in features)

    X_full = train[features].values.astype(np.float64)
    y_full = train["Y"].values.astype(int)
    X_test = test[features].values.astype(np.float64)

    print(f"\nTrain: {X_full.shape}  Positives: {y_full.sum()} ({y_full.mean()*100:.2f}%)")
    print(f"Test:  {X_test.shape}")

    oof_lgb = np.zeros(len(train))
    oof_xgb = np.zeros(len(train))
    oof_cat = np.zeros(len(train))
    test_lgb = np.zeros(len(test))
    test_xgb = np.zeros(len(test))
    test_cat = np.zeros(len(test))

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    fold_aucs_lgb = []
    fold_aucs_xgb = []
    fold_aucs_cat = []
    fold_variants = []
    fold_synth_counts = []

    print("\n--- CV Loop ---")
    for fold_i, (tr_idx, va_idx) in enumerate(skf.split(X_full, y_full)):
        print(f"\n[Fold {fold_i+1}/5]")
        X_tr_raw = X_full[tr_idx]
        y_tr_raw = y_full[tr_idx]
        X_va = X_full[va_idx]
        y_va = y_full[va_idx]

        X_tr, y_tr, variant = resample_fold(X_tr_raw, y_tr_raw, fold_i + 1)
        fold_variants.append(variant)
        fold_synth_counts.append(int(y_tr.sum()) - int(y_tr_raw.sum()))
        print(f"  Train size after resampling: {len(X_tr)} rows ({int(y_tr.sum())} pos)")

        # LightGBM
        lgb_model = lgb.LGBMClassifier(**LGB_PARAMS)
        lgb_model.fit(
            X_tr, y_tr,
            eval_set=[(X_va, y_va)],
            callbacks=[lgb.early_stopping(50, verbose=False), lgb.log_evaluation(period=-1)],
        )
        oof_lgb[va_idx] = lgb_model.predict_proba(X_va)[:, 1]
        test_lgb += lgb_model.predict_proba(X_test)[:, 1] / 5
        auc_lgb = roc_auc_score(y_va, oof_lgb[va_idx])
        fold_aucs_lgb.append(auc_lgb)
        print(f"  LGB OOF AUC fold {fold_i+1}: {auc_lgb:.4f}")

        # XGBoost
        xgb_model = xgb.XGBClassifier(**XGB_PARAMS)
        xgb_model.fit(
            X_tr, y_tr,
            eval_set=[(X_va, y_va)],
            verbose=False,
        )
        oof_xgb[va_idx] = xgb_model.predict_proba(X_va)[:, 1]
        test_xgb += xgb_model.predict_proba(X_test)[:, 1] / 5
        auc_xgb = roc_auc_score(y_va, oof_xgb[va_idx])
        fold_aucs_xgb.append(auc_xgb)
        print(f"  XGB OOF AUC fold {fold_i+1}: {auc_xgb:.4f}")

        # CatBoost
        cat_model = CatBoostClassifier(**CAT_PARAMS)
        cat_model.fit(
            X_tr, y_tr,
            eval_set=(X_va, y_va),
            early_stopping_rounds=50,
        )
        oof_cat[va_idx] = cat_model.predict_proba(X_va)[:, 1]
        test_cat += cat_model.predict_proba(X_test)[:, 1] / 5
        auc_cat = roc_auc_score(y_va, oof_cat[va_idx])
        fold_aucs_cat.append(auc_cat)
        print(f"  CAT OOF AUC fold {fold_i+1}: {auc_cat:.4f}")

    print("\n--- Fold Summary ---")
    print(f"SMOTE variants used: {fold_variants}")
    print(f"Synthetic samples per fold: {fold_synth_counts}  (avg: {np.mean(fold_synth_counts):.1f})")
    print(f"LGB OOF AUC: {[round(a,4) for a in fold_aucs_lgb]}  mean={np.mean(fold_aucs_lgb):.4f}")
    print(f"XGB OOF AUC: {[round(a,4) for a in fold_aucs_xgb]}  mean={np.mean(fold_aucs_xgb):.4f}")
    print(f"CAT OOF AUC: {[round(a,4) for a in fold_aucs_cat]}  mean={np.mean(fold_aucs_cat):.4f}")

    # Meta-learner
    print("\n--- Meta-learner (LR + Platt) ---")
    X_meta_oof  = np.column_stack([oof_lgb, oof_xgb, oof_cat])
    X_meta_test = np.column_stack([test_lgb, test_xgb, test_cat])

    base_meta = LogisticRegression(C=1.0, max_iter=1000, random_state=42)
    meta = CalibratedClassifierCV(base_meta, method="sigmoid", cv=5)
    meta.fit(X_meta_oof, y_full)

    p_oof  = meta.predict_proba(X_meta_oof)[:, 1]
    p_test = meta.predict_proba(X_meta_test)[:, 1]

    meta_auc = roc_auc_score(y_full, p_oof)
    print(f"Meta OOF AUC: {meta_auc:.4f}")

    # Threshold sweep
    print("\n--- Threshold Sweep ---")
    uniq = np.sort(np.unique(np.concatenate([p_oof, [0.0, 1.0]])))
    cuts = np.r_[uniq[0] - 1e-6, 0.5 * (uniq[:-1] + uniq[1:]), uniq[-1] + 1e-6]

    best_T, best_score, best_recall, best_prec, best_npos = 0.0, 0.0, 0.0, 0.0, 0
    sweep_rows = []

    for t in cuts:
        pred = (p_oof >= t).astype(int)
        tp = int(((pred == 1) & (y_full == 1)).sum())
        fp = int(((pred == 1) & (y_full == 0)).sum())
        fn = int(((pred == 0) & (y_full == 1)).sum())
        r  = tp / (tp + fn) if (tp + fn) else 0.0
        p  = tp / (tp + fp) if (tp + fp) else 0.0
        s  = (r + p) / 2.0 * 100.0
        sweep_rows.append({"threshold": t, "score": s, "recall": r, "precision": p, "n_pos": tp + fp})
        if s > best_score:
            best_score, best_T = s, t
            best_recall, best_prec, best_npos = r, p, tp + fp

    sweep_df = pd.DataFrame(sweep_rows)
    sweep_df.to_csv(V26_DIR / "threshold_sweep_v26.csv", index=False)

    print(f"Best threshold: {best_T:.8f}")
    print(f"OOF score: {best_score:.4f}  Recall: {best_recall:.4f}  Precision: {best_prec:.4f}  N_pos: {best_npos}")

    v4_score = 54.31
    delta = best_score - v4_score
    print(f"Delta vs V4 (54.31): {delta:+.4f}")

    # Save OOF parquet
    oof_df = pd.DataFrame({
        "CoilID":   train["CoilID"].values,
        "oof_meta": p_oof,
        "Y":        y_full,
    })
    oof_df.to_parquet(V26_DIR / "oof_v26.parquet", index=False)
    print(f"\nSaved oof_v26.parquet ({len(oof_df)} rows)")

    # Save threshold JSON
    threshold_data = {
        "chosen_threshold": best_T,
        "strategy": "maximize_(recall+precision)/2_exact_unique_thresholds",
        "predicted_lb_score": best_score,
        "oof_recall": best_recall,
        "oof_precision": best_prec,
        "oof_n_positives": best_npos,
        "oof_total": int(len(y_full)),
        "oof_positive_rate": float(best_npos / len(y_full)),
        "meta_oof_auc": float(meta_auc),
        "fold_aucs_lgb": [float(a) for a in fold_aucs_lgb],
        "fold_aucs_xgb": [float(a) for a in fold_aucs_xgb],
        "fold_aucs_cat": [float(a) for a in fold_aucs_cat],
        "mean_auc_lgb": float(np.mean(fold_aucs_lgb)),
        "mean_auc_xgb": float(np.mean(fold_aucs_xgb)),
        "mean_auc_cat": float(np.mean(fold_aucs_cat)),
        "smote_variants_per_fold": fold_variants,
        "synthetic_samples_per_fold": [int(c) for c in fold_synth_counts],
        "avg_synthetic_samples": float(np.mean(fold_synth_counts)),
        "v4_oof_score": v4_score,
        "delta_vs_v4": float(delta),
    }
    (V26_DIR / "chosen_threshold_v26.json").write_text(json.dumps(threshold_data, indent=2))
    print("Saved chosen_threshold_v26.json")

    # Submission CSV
    sub = pd.DataFrame({
        "CoilID": test["CoilID"].values,
        "Y": (p_test >= best_T).astype(int),
    })
    assert sub.shape == (339, 2)
    assert sub["Y"].isin([0, 1]).all()
    sub.to_csv(V26_DIR / "expected_submission.csv", index=False)
    n_pos_test = int(sub["Y"].sum())
    print(f"Saved expected_submission.csv: {n_pos_test}/339 positives ({n_pos_test/339*100:.1f}%)")

    print("\n" + "=" * 65)
    print("V26 SUMMARY")
    print("=" * 65)
    print(f"  Primary SMOTE variant:   {fold_variants[0]} (fold 1)")
    print(f"  Variants across folds:   {fold_variants}")
    print(f"  Avg synthetic samples:   {np.mean(fold_synth_counts):.1f}")
    print(f"  LGB mean OOF AUC:        {np.mean(fold_aucs_lgb):.4f}")
    print(f"  XGB mean OOF AUC:        {np.mean(fold_aucs_xgb):.4f}")
    print(f"  CAT mean OOF AUC:        {np.mean(fold_aucs_cat):.4f}")
    print(f"  Meta OOF AUC:            {meta_auc:.4f}")
    print(f"  OOF (R+P)/2 score:       {best_score:.4f}")
    print(f"  Delta vs V4 (54.31):     {delta:+.4f}")
    print(f"  Threshold:               {best_T:.8f}")
    print(f"  Test positives:          {n_pos_test}/339 ({n_pos_test/339*100:.1f}%)")
    print(f"  Calibrated LB est:       {best_score + 2.67:.4f}  (V4 LB=56.98)")
    print("=" * 65)


if __name__ == "__main__":
    main()
